[package]
name = "rpc_ch32x0_afio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open-enum.workspace = true
rpc.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
