[target]
device = "ch32x035"
clock = 8000000

[kernel.memory]
data = 1024
stack = 1024

[tasks.idle]
boot = true
priority = 255
memory = { data = 0, stack = 0 }

[tasks.ch32x0_afio]
boot = true
priority = 254
memory = { data = 0, stack = 1024 }
peripherals = [ "afio" ]

[tasks.ch32x0_rcc]
boot = true
priority = 254
memory = { data = 0, stack = 1024 }
peripherals = [ "rcc" ]

[tasks.adb_host]
boot = true
priority = 1
memory = { data = 0, stack = 1024 }
peripherals = [ "gpioa" ]

[tasks.usb_keyboard]
boot = true
priority = 0
memory = { data = 260, stack = 1788 }
peripherals = [ "usbfs", "usart1" ]
