[package]
name = "stack_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
either.workspace = true
llvm-ir.workspace = true
llvm-sys.workspace = true
petgraph.workspace = true
stack-sizes.workspace = true

[lints]
workspace = true
