[package]
name = "rtos_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { version = "2.0.27", features = [ "full" ] }

[lints]
workspace = true
