[package]
name = "rtos_llvm_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-plugin.workspace = true
llvm-sys.workspace = true

[lints]
workspace = true
